# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='User',
            field=models.CharField(default=b'null', max_length=255),
        ),
    ]
