# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMManager', '0002_virtualmachine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='State',
            field=models.CharField(default='running', max_length=50),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='User',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
