# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMManager', '0004_virtualmachine_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='SSH_User',
            field=models.CharField(default='null', max_length=5),
        ),
    ]
