# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMManager', '0005_virtualmachine_ssh_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='Backupinterval',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
