# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 07:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2017, 11, 21, 7, 55, 30, 14992, tzinfo=utc), verbose_name='Geboortedatum'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Voornaam'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='surname',
            field=models.CharField(default='', max_length=255, verbose_name='Tussenvoegsel + Achternaam'),
        ),
    ]
