# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20171121_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='insertion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tussenvoegsel'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2017, 11, 21, 10, 12, 6, 168882, tzinfo=utc), verbose_name='Geboortedatum'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='John', max_length=255, verbose_name='Voornaam'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='surname',
            field=models.CharField(default='Doe', max_length=255, verbose_name='Tussenvoegsel + Achternaam'),
        ),
    ]
