# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20171121_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='adres',
            field=models.CharField(default='SomeStreet, SomeCity', max_length=255, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='company',
            field=models.CharField(default='-', max_length=255, verbose_name='Bedrijf'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.CharField(default='Nederland', max_length=255, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='iban',
            field=models.CharField(default='ABCD010123456789', max_length=16, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phonenumber',
            field=models.IntegerField(default='0612345678', verbose_name='Telefoonnummer'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='postalcode',
            field=models.CharField(default='1234AB', max_length=6, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2017, 11, 27, 11, 45, 43, 256252, tzinfo=utc), verbose_name='Geboortedatum'),
        ),
    ]
