# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20171127_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profilepic',
            field=models.ImageField(default='uploads/profiles/no-profile.img', upload_to='uploads/profiles/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2017, 11, 27, 12, 23, 39, 254674, tzinfo=utc), verbose_name='Geboortedatum'),
        ),
    ]
