# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 13:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20171127_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2017, 11, 27, 13, 53, 40, 878000, tzinfo=utc), verbose_name='Geboortedatum'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profilepic',
            field=models.ImageField(default='/profiles/no-profile.png', upload_to='profiles/'),
        ),
    ]
