
GET http://localhost:5000/ HTTP/1.1

###

POST http://localhost:5000/V1.0/createvm HTTP/1.1
Content-Type: application/json

{
    "cores": 2,
    "memory": 200,
    "storage": 20,
    "name": "test",
    "os": "ubuntu"
}

###

POST http://localhost:5000/V1.0/reboot HTTP/1.1
Content-Type: application/json

{"uuid": "3b2690aa-81ac-490f-a111-0af73b9694a4"}

###

POST http://localhost:5000/V1.0/shutdown HTTP/1.1
Content-Type: application/json

{"uuid": "3b2690aa-81ac-490f-a111-0af73b9694a4"}

###

POST http://localhost:5000/V1.0/start HTTP/1.1
Content-Type: application/json

{"uuid": "3b2690aa-81ac-490f-a111-0af73b9694a4"}

###
POST http://localhost:5000/V1.0/destroy HTTP/1.1
Content-Type: application/json

{"uuid": "dfa8b4bb-58fe-4a0a-a2d0-73ab1446ccf8"}


###

GET http://localhost:5000/V1.0/list HTTP/1.1